---
all:
  children:
    servers:
       hosts:
         pcm1:
           ansible_host: "192.168.7.150"
           ansible_private_key_file: ".vagrant/machines/pcm1/virtualbox/private_key"
         pcm2:
           ansible_host: "192.168.7.151"
           ansible_private_key_file: ".vagrant/machines/pcm2/virtualbox/private_key"
         pcm3:
           ansible_host: "192.168.7.152"
           ansible_private_key_file: ".vagrant/machines/pcm3/virtualbox/private_key" 
       vars:
         virtualbox_host: "192.168.88.241"
         virtualbox_host_username: "mbfx"
         virtualbox_host_password: "strong_pass"
    server-iscsi:
      hosts:
         iscsi:
           ansible_host: "192.168.7.153"
           ansible_private_key_file: ".vagrant/machines/iscsi/virtualbox/private_key" 
  vars:
    domain: "mydomain.test"
    ntp_timezone: "UTC"
    pcs_password: "strong_pass" # cluster user: hacluster
    cluster_name: "hacluster"
...
