---
- hosts: iscsi
  tags: target
  become: true
  roles:
    - role: iscsi-target

- name: cluster prepare
  hosts: servers
  become: true
  tags:
    - servers
  roles:
    - sedovandrew.nginx
    - role: fence_agents
    - role: pacemaker
    - role: iscsi-client

- name: discover iscsi
  become: true
  hosts: servers
  tags: iclient
  tasks: 
    - name: change iqn
      lineinfile:
        path: /etc/iscsi/initiatorname.iscsi
        regexp: '^InitiatorName=.*'
        line: 'InitiatorName=iqn.2021-09.ru.otus:{{ inventory_hostname }}'
    - name: iscsiadm
      shell: |
        iscsiadm -m discovery -t st -p 192.168.8.153
        iscsiadm -m discovery -t st -p 192.168.7.153
        iscsiadm -m node -l -T iqn.2021-09.ru.otus:storage.target00
    - name: iscsid start
      service:
        name: iscsid
        state: started

- name: Configure cLVM and GFS2
  become: true
  hosts: pcm1
  tasks:
    - name: Configure pacemaker
      shell: |
        pcs cluster start --all
        pcs property set stonith-enabled=false
        pcs property set no-quorum-policy=freeze
        pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
        pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
        pcs constraint order start dlm-clone then clvmd-clone
    - name: Configure cLVM
      shell: |
        sleep 120
        pvcreate /dev/mapper/mpatha
        vgcreate -Ay -cy cluster_vg /dev/mapper/mpatha
        lvcreate -L900M -n cluster_lv cluster_vg
    - name: Configure GFS2
      shell: |
        mkfs.gfs2 -O -j3 -p lock_dlm -t otusha:gfs2 /dev/cluster_vg/cluster_lv
        pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2"  fstype="gfs2" "options=noatime" op monitor interval=10s  on-fail=ignore clone interleave=true
        pcs constraint order start clvmd-clone then clusterfs-clone --force
        pcs constraint colocation add clusterfs-clone with clvmd-clone
