---
- name: check os version
  fail: msg='OS is NOT CentOS 7.x'
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '7'

- name: install iscsi target
  yum:
    state: present
    name:
      - targetcli

- name: targetcli
  shell: |
    targetcli /backstores/block create disk01 /dev/sdb
    targetcli /backstores/block create disk02 /dev/sdc
    targetcli /iscsi create iqn.2021-09.ru.otus:storage.target00
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1/portals create 0.0.0.0
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1/luns create /backstores/block/disk01 lun=1 
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1/luns create /backstores/block/disk01 lun=2
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1 set attribute authentication=0
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1/acls create iqn.2021-09.ru.otus:pcm1
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1/acls create iqn.2021-09.ru.otus:pcm2
    targetcli /iscsi/iqn.2021-09.ru.otus:storage.target00/tpg1/acls create iqn.2021-09.ru.otus:pcm3

